name: corbit_mono
description: Corbit Mono - A futuristic open-source monospace developer font for Flutter.
version: 1.0.0
homepage: https://corbit.tech
repository: https://github.com/corbittechnologies/corbit-font

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  fonts:
    - family: CorbitMono
      fonts:
        - asset: fonts/CorbitMono.ttf
